### ISSUE TITLE
About camera agnostic

### ISSUE THREAD

**Issue by YangJae96** [chenhao2345/ICE#4]
Hello. Thank you for your great work.

How can I set the camera-aware or camera-agnostic during training?

For example, I do not want to use the camera ID in your method.

Is camera-agnostic not using camera ID at all??

**Comment by chenhao2345** [comment]
Hi. You can simply remove loss_cam in trainers.py so that it will not optimize camera-aware loss. 
https://github.com/chenhao2345/ICE/blob/a206eb9a97ad431ab9d9cf38cdcf5ab6fdc6ad1c/ice/trainers.py#L161

**Comment by YangJae96** [comment]
Thank you!!
