### ISSUE TITLE
About mini-batch shuffling.

### ISSUE THREAD

**Issue by YangJae96** [chenhao2345/ICE#6]
![image](https://user-images.githubusercontent.com/57695621/148936080-736128ac-f243-43c3-861a-145226ce041e.png)
![image](https://user-images.githubusercontent.com/57695621/148936113-51516ee7-7def-4b56-80ce-3600f0e8f260.png)

Hi, I have some question about the implementation.

Why do you shuffle and reverse the mini-batch order before feeding it into the 
online encoder and momentum encoder like the above code??
![image](https://user-images.githubusercontent.com/57695621/148936396-954d36bc-edec-4b81-9f0f-779d26da2112.png)

**Comment by chenhao2345** [comment]
This is a technique introduced in [Kaiming's MoCo paper](https://arxiv.org/pdf/1911.05722.pdf) Page 4. This technique helps to stabilize batch normalization training on multiple GPUs.
