### ISSUE TITLE
Memory bank update problem

### ISSUE THREAD

**Issue by Git-Yxt** [chenhao2345/ICE#7]
why didn't the author update the camera-aware memory bank in an epoch?

**Comment by chenhao2345** [comment]
We update the memory bank every 400 iterations in the paper. Actually, we tested a higher update frequency, such as every 200 or 300 iterations, but the final results remain almost the same.

**Comment by Git-Yxt** [comment]
Thanks for your explanation. But I still have the question. I think you mean that the memory bank's updating process is conducted with re-clustering at the beginning of each epoch. Why didn't you use momentum to update the memory bank  as some papers do? Is there any difference? Thank you for your reply.

**Comment by chenhao2345** [comment]
I know some papers use momentum on feature vectors in the memory bank. I use momentum on network weights. I remember that I tested both and the results are also similar.

**Comment by Git-Yxt** [comment]
Thanks for your detailed explanation.
